version: '3'
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env

  # Using pgadmin with docker
  # References
  # - https://www.pgadmin.org/download/pgadmin-4-container/
  # - https://hub.docker.com/r/dpage/pgadmin4/
  # - https://renatogroffe.medium.com/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '16543:80'
    depends_on:
      - postgres_db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
